name: Run Notebook

on:
  push:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install notebook ipykernel nbconvert

      - name: Create and Register Kernel
        run: |
          python -m ipykernel install --user --name python3

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/_init_.ipynb --output output.ipynb

